"""
Prometheus metrics configuration and collection.

This module provides centralized metrics collection for monitoring
query latency, throughput, error rates, and custom application metrics.
"""

from typing import Optional
from prometheus_client import Counter, Histogram, Gauge, Info, generate_latest, REGISTRY
from prometheus_client import CollectorRegistry
import time
from contextlib import contextmanager


# Create a custom registry for better control
metrics_registry = CollectorRegistry()

# API Gateway Metrics
api_requests_total = Counter(
    'api_requests_total',
    'Total number of API requests',
    ['method', 'endpoint', 'status'],
    registry=metrics_registry
)

api_request_duration_seconds = Histogram(
    'api_request_duration_seconds',
    'API request duration in seconds',
    ['method', 'endpoint'],
    buckets=(0.01, 0.05, 0.1, 0.5, 1.0, 2.5, 5.0, 10.0),
    registry=metrics_registry
)

# Query Processing Metrics
query_processing_duration_seconds = Histogram(
    'query_processing_duration_seconds',
    'RAG query processing duration in seconds',
    ['stage'],
    buckets=(0.01, 0.05, 0.1, 0.5, 1.0, 2.5, 5.0, 10.0, 30.0),
    registry=metrics_registry
)

query_total = Counter(
    'query_total',
    'Total number of queries processed',
    ['status'],
    registry=metrics_registry
)

query_errors_total = Counter(
    'query_errors_total',
    'Total number of query errors',
    ['error_type'],
    registry=metrics_registry
)

# Embedding Generation Metrics
embedding_generation_duration_seconds = Histogram(
    'embedding_generation_duration_seconds',
    'Embedding generation duration in seconds',
    ['batch_size_bucket'],
    buckets=(0.01, 0.05, 0.1, 0.5, 1.0, 2.5, 5.0),
    registry=metrics_registry
)

embedding_generation_total = Counter(
    'embedding_generation_total',
    'Total number of embeddings generated',
    registry=metrics_registry
)

embeddings_batch_size = Histogram(
    'embeddings_batch_size',
    'Size of embedding batches',
    buckets=(1, 5, 10, 20, 50, 100),
    registry=metrics_registry
)

# Vector Search Metrics
vector_search_duration_seconds = Histogram(
    'vector_search_duration_seconds',
    'Vector search duration in seconds',
    ['top_k_bucket'],
    buckets=(0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0),
    registry=metrics_registry
)

vector_search_total = Counter(
    'vector_search_total',
    'Total number of vector searches',
    registry=metrics_registry
)

vector_search_results_count = Histogram(
    'vector_search_results_count',
    'Number of results returned by vector search',
    buckets=(0, 1, 5, 10, 20, 50),
    registry=metrics_registry
)

# LLM Service Metrics
llm_generation_duration_seconds = Histogram(
    'llm_generation_duration_seconds',
    'LLM response generation duration in seconds',
    buckets=(0.5, 1.0, 2.5, 5.0, 10.0, 30.0, 60.0),
    registry=metrics_registry
)

llm_generation_total = Counter(
    'llm_generation_total',
    'Total number of LLM generations',
    ['status'],
    registry=metrics_registry
)

llm_tokens_generated = Counter(
    'llm_tokens_generated',
    'Total number of tokens generated by LLM',
    registry=metrics_registry
)

# LLM Guard Metrics
llm_guard_checks_total = Counter(
    'llm_guard_checks_total',
    'Total number of LLM Guard safety checks',
    ['check_type', 'result'],
    registry=metrics_registry
)

llm_guard_rejections_total = Counter(
    'llm_guard_rejections_total',
    'Total number of rejected inputs/outputs',
    ['check_type', 'reason'],
    registry=metrics_registry
)

# Document Ingestion Metrics
document_ingestion_duration_seconds = Histogram(
    'document_ingestion_duration_seconds',
    'Document ingestion duration in seconds',
    buckets=(0.1, 0.5, 1.0, 5.0, 10.0, 30.0, 60.0),
    registry=metrics_registry
)

document_ingestion_total = Counter(
    'document_ingestion_total',
    'Total number of documents ingested',
    ['status'],
    registry=metrics_registry
)

# Cache Metrics (Requirement 14.4)
cache_hits_total = Counter(
    'cache_hits_total',
    'Total number of cache hits',
    ['cache_type'],
    registry=metrics_registry
)

cache_misses_total = Counter(
    'cache_misses_total',
    'Total number of cache misses',
    ['cache_type'],
    registry=metrics_registry
)

cache_operations_duration_seconds = Histogram(
    'cache_operations_duration_seconds',
    'Cache operation duration in seconds',
    ['operation', 'cache_type'],
    buckets=(0.001, 0.005, 0.01, 0.05, 0.1),
    registry=metrics_registry
)

chunks_created_total = Counter(
    'chunks_created_total',
    'Total number of text chunks created',
    registry=metrics_registry
)

# Database Metrics
database_query_duration_seconds = Histogram(
    'database_query_duration_seconds',
    'Database query duration in seconds',
    ['operation'],
    buckets=(0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0),
    registry=metrics_registry
)

database_connections_active = Gauge(
    'database_connections_active',
    'Number of active database connections',
    registry=metrics_registry
)

# Conversation Metrics
conversations_active = Gauge(
    'conversations_active',
    'Number of active conversations',
    registry=metrics_registry
)

messages_total = Counter(
    'messages_total',
    'Total number of messages stored',
    ['role'],
    registry=metrics_registry
)

# System Info
system_info = Info(
    'system',
    'System information',
    registry=metrics_registry
)


# Context managers for timing operations
@contextmanager
def track_time(histogram: Histogram, labels: Optional[dict] = None):
    """
    Context manager to track operation duration.
    
    Usage:
        with track_time(query_processing_duration_seconds, {'stage': 'embedding'}):
            # operation code
            pass
    """
    start_time = time.time()
    try:
        yield
    finally:
        duration = time.time() - start_time
        if labels:
            histogram.labels(**labels).observe(duration)
        else:
            histogram.observe(duration)


@contextmanager
def track_api_request(method: str, endpoint: str):
    """
    Context manager to track API request metrics.
    
    Usage:
        with track_api_request('POST', '/api/query') as tracker:
            # request handling code
            tracker.set_status(200)
    """
    start_time = time.time()
    
    class RequestTracker:
        def __init__(self):
            self.status = 500  # Default to error
        
        def set_status(self, status: int):
            self.status = status
    
    tracker = RequestTracker()
    
    try:
        yield tracker
    finally:
        duration = time.time() - start_time
        api_request_duration_seconds.labels(method=method, endpoint=endpoint).observe(duration)
        api_requests_total.labels(method=method, endpoint=endpoint, status=tracker.status).inc()


# Helper functions for common metrics operations
def record_query_success(duration_seconds: float):
    """Record a successful query."""
    query_total.labels(status='success').inc()
    query_processing_duration_seconds.labels(stage='total').observe(duration_seconds)


def record_query_error(error_type: str):
    """Record a query error."""
    query_total.labels(status='error').inc()
    query_errors_total.labels(error_type=error_type).inc()


def record_embedding_generation(duration_seconds: float, batch_size: int = 1):
    """Record embedding generation metrics."""
    embedding_generation_total.inc(batch_size)
    embeddings_batch_size.observe(batch_size)
    
    # Bucket batch size for histogram label
    if batch_size == 1:
        bucket = 'single'
    elif batch_size <= 10:
        bucket = 'small'
    elif batch_size <= 50:
        bucket = 'medium'
    else:
        bucket = 'large'
    
    embedding_generation_duration_seconds.labels(batch_size_bucket=bucket).observe(duration_seconds)


def record_vector_search(duration_seconds: float, top_k: int, results_count: int):
    """Record vector search metrics."""
    vector_search_total.inc()
    vector_search_results_count.observe(results_count)
    
    # Bucket top_k for histogram label
    if top_k <= 5:
        bucket = 'small'
    elif top_k <= 20:
        bucket = 'medium'
    else:
        bucket = 'large'
    
    vector_search_duration_seconds.labels(top_k_bucket=bucket).observe(duration_seconds)


def record_llm_generation(duration_seconds: float, tokens_generated: int, success: bool = True):
    """Record LLM generation metrics."""
    status = 'success' if success else 'error'
    llm_generation_total.labels(status=status).inc()
    llm_generation_duration_seconds.observe(duration_seconds)
    if success:
        llm_tokens_generated.inc(tokens_generated)


def record_llm_guard_check(check_type: str, passed: bool, reason: Optional[str] = None):
    """Record LLM Guard safety check metrics."""
    result = 'passed' if passed else 'rejected'
    llm_guard_checks_total.labels(check_type=check_type, result=result).inc()
    
    if not passed and reason:
        llm_guard_rejections_total.labels(check_type=check_type, reason=reason).inc()


def record_document_ingestion(duration_seconds: float, chunks_count: int, success: bool = True):
    """Record document ingestion metrics."""
    status = 'success' if success else 'error'
    document_ingestion_total.labels(status=status).inc()
    document_ingestion_duration_seconds.observe(duration_seconds)
    if success:
        chunks_created_total.inc(chunks_count)


def record_message(role: str):
    """Record a message being stored."""
    messages_total.labels(role=role).inc()


def record_cache_hit(cache_type: str):
    """
    Record a cache hit.
    
    Args:
        cache_type: Type of cache ('embedding' or 'response')
        
    Requirements: 14.4
    """
    cache_hits_total.labels(cache_type=cache_type).inc()


def record_cache_miss(cache_type: str):
    """
    Record a cache miss.
    
    Args:
        cache_type: Type of cache ('embedding' or 'response')
        
    Requirements: 14.4
    """
    cache_misses_total.labels(cache_type=cache_type).inc()


def record_cache_operation(operation: str, cache_type: str, duration_seconds: float):
    """
    Record a cache operation duration.
    
    Args:
        operation: Operation type ('get' or 'set')
        cache_type: Type of cache ('embedding' or 'response')
        duration_seconds: Operation duration in seconds
        
    Requirements: 14.4
    """
    cache_operations_duration_seconds.labels(
        operation=operation,
        cache_type=cache_type
    ).observe(duration_seconds)


def set_system_info(service_name: str, version: str, **kwargs):
    """Set system information."""
    info_dict = {
        'service': service_name,
        'version': version,
        **kwargs
    }
    system_info.info(info_dict)


def get_metrics() -> bytes:
    """
    Get current metrics in Prometheus format.
    
    Returns:
        Metrics data in Prometheus text format
    """
    return generate_latest(metrics_registry)
